spring: 
  application: 
    name: country-service
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server: 
  port: 6060
info:
  description: Country-Service Client
  name: Country-Service

eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
  instance: 
    hostname: localhost 
    preferIpAddress: true
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/Country
    health-check-url: http://${eureka.instance.hostname}:${server.port}/health 
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  register-with-eureka: false
  fetch-registry: false

country:
  amqp:
    queue: country-queue
