spring: 
  application: 
    name: city-service
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server: 
  port: 9080
info:
  description: City-Service Client
  name: City-Service

eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
  instance: 
    hostname: localhost 
    preferIpAddress: true
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/City
    health-check-url: http://${eureka.instance.hostname}:${server.port}/health 
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  register-with-eureka: false
  fetch-registry: false

city:
  amqp:
    queue: city-queue
